---
- name: Converge
  hosts: all
  become: true
  vars:
    vernemq__configs:
      accept_eula: "yes"
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"
      changed_when: false
  roles:
    - role: ngine_io.vernemq
