---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.

name: Release
"on":
  release:
    types: [created]

defaults:
  run:
    working-directory: ngine_io.vernemq

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: ngine_io.vernemq

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
        run: >-
          ansible-galaxy role import
          --token "$ANSIBLE_GALAXY_API_KEY"
          --role-name vernemq
          $(echo ${{ github.repository }} | cut -d/ -f1)
          $(echo ${{ github.repository }} | cut -d/ -f2)
